# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: broken_package_name.proto
# typed: strict

#
# This protobuf does not define any services. This file is included to ensure consistent output files
# which makes deterministic build systems like bazel happy.
