# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: lowercase.proto
# typed: strict

#
# This protobuf does not define any services. This file is included to ensure consistent output files
# which makes deterministic build systems like bazel happy.
